version: '3.3'

services:
  go-api:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    container_name: autotester-go
    ports:
      - "8081:8081"
    environment:
      - TIMEOUT=3
      - FRONTEND_URL=http://frontend:3001
    volumes:
      - ./logs:/app/logs
    networks:
      - autotester-network
    depends_on:
      - webtester

  webtester:
    build:
      context: .
      dockerfile: webtester/Dockerfile
    container_name: autotester-webtester
    ports:
      - "3000:3000"
    networks:
      - autotester-network
    environment:
      - OPENAI_API_KEY=sk-0M12tbkrnKubF86nHyKPKidkqoqfNzei

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.flutter
    container_name: autotester-frontend
    networks:
      - autotester-network
    # УДАЛЕН volumes (сборка происходит в Dockerfile)
    command: sh -c "flutter build web && tail -f /dev/null"  # Автосборка при запуске

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build/web:/usr/share/nginx/html:ro  # Прямое монтирование билда
    depends_on:
      - frontend  # Ждем сборки фронтенда
      - go-api
    networks:
      - autotester-network

networks:
  autotester-network:
    driver: bridge

# УДАЛЕН volumes (ненужный именованный том)
